## 应用名
spring:
  application:
    name: eureka-consumer-feign-hystrix

## 端口
server:
  port: 1008

## 服务注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

## 断路器开关
feign:
  hystrix:
    enabled: true

