## 应用名
spring:
  application:
    name: zuul-gateway-service-route

## 端口
server:
  port: 1101

## 服务路由配置
zuul:
  routes:
    users:
      path: /eureka-client/**
      serviceId: eureka-client

## 服务注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
